name: PowerShell script
author: Freddy Kristiansen
permissions:
  contents: write
  pull-requests: write
  workflows: write
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '{}'
  templateUrl:
    description: URL of the template repository (default is the template repository used to create the repository)
    required: false
    default: ''
  templateBranch:
    description: Branch in template repository to use for the update (default is the default branch)
    required: false
    default: ''
  update:
    description: Set this input to Y in order to update AL-Go System Files if needed
    required: false
    default: 'N'
  directCommit:
    description: Direct Commit (Y/N)
    required: false
    default: 'N'
runs:
  using: composite
  steps:
    - run: try { ${{ github.action_path }}/CheckForUpdates.ps1 -actor '${{ inputs.actor }}' -token '${{ inputs.token }}' -parentTelemetryScopeJson '${{ inputs.parentTelemetryScopeJson }}' -templateUrl '${{ inputs.templateUrl }}' -templateBranch '${{ inputs.templateBranch }}' -update ('${{ inputs.update }}' -eq 'Y') -directCommit ('${{ inputs.directCommit }}' -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
      shell: PowerShell
branding:
  icon: terminal
  color: blue
