name: INECTA CI/CD

on:
  workflow_dispatch:

jobs:
  BranchCutOff:
    uses: ./.github/workflows/BranchCutOff.yaml
    secrets: inherit

  Build:
    needs: [ BranchCutOff ]
    uses: ./.github/workflows/CICD.yaml
    secrets: inherit

  ReleaseVersion:
    runs-on: [ windows-latest ]
    needs: [ BranchCutOff, Build ]
    outputs:
      RelVerTag: ${{ steps.RelVerTag.outputs.RelVerTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get release version
        id: RelVerTag
        shell: PowerShell
        run: |
          $releaseversion = Get-Content -Path "$ENV:GITHUB_WORKSPACE\release.version"
          Write-Output ::set-output name=RelVerTag::$($releaseversion)

  Release:
    needs: [ BranchCutOff, Build, ReleaseVersion ]
    uses: ./.github/workflows/CreateRelease.yaml
    with:
      name: ${{ jobs.ReleaseVersion.outputs.RelVerTag }}
      tag: ${{ jobs.ReleaseVersion.outputs.RelVerTag }}
      createReleaseBranch: "Y"
      directCommit: "Y"
    secrets: inherit
