name: INECTA CI/CD

on:
  workflow_dispatch:

jobs:
  BranchCutOff:
    uses: ./.github/workflows/BranchCutOff.yaml
    secrets: inherit

  Build:
    needs: [ BranchCutOff ]
    uses: ./.github/workflows/CICD.yaml
    secrets: inherit

  Release:
    needs: [ BranchCutOff, Build ]
    uses: ./.github/workflows/InectaRelease.yaml
    secrets: inherit
