name: Branch Cut Off2

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: Specify the environment json for the customer repository to parse the granules from.
        required: true
        default: "untitled.json"

permissions:
  contents: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [windows-latest]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v1.5
        with:
          eventId: "DO0091"

  BranchCutOff2:
    runs-on: [windows-latest]
    needs: [Initialization]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create cut off branch
        uses: iNECTA/AL-Go-Actions-INECTA/BranchCutOff2@main
        env:
          secrets: ${{ toJson(secrets) }}

      - name: Update customer repository
        uses: iNECTA/AL-Go-Actions-INECTA/UpdateCustomerRepository@main

  PostProcess:
    if: always()
    runs-on: [windows-latest]
    needs: [Initialization, BranchCutOff2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v1.5
        with:
          eventId: "DO0091"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
