name: Branch Clone

on:
  workflow_call:
    inputs:
      Environment:
        description: Specify the name of the environment to parse the granules from.
        required: true
        type: string
        default: "untitled"
      Tag:
        description: Specify the value of the tag.
        required: true
        type: string
        default: "123.456"
  workflow_dispatch:
    inputs:
      Environment:
        description: Specify the name of the environment to parse the granules from.
        required: true
        default: "untitled"
      Tag:
        description: Specify the value of the tag.
        required: true
        default: "123.456"

permissions:
  contents: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [windows-latest]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v1.5
        with:
          eventId: "DO0091"

  BranchClone:
    runs-on: [windows-latest]
    needs: [Initialization]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create cut off branch
        uses: iNECTA/AL-Go-Actions-INECTA/BranchCutOff2@main
        env:
          envInput: ${{ github.event.inputs.Environment }}
          envTag: ${{ github.event.inputs.Tag }}
          repoName: ${{ github.event.repository.name }}
          secrets: ${{ toJson(secrets) }}

  PostProcess:
    if: always()
    runs-on: [windows-latest]
    needs: [Initialization, BranchClone]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v1.5
        with:
          eventId: "DO0091"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
