name: Update AL-Go System Files

on:
  schedule:
    - cron: '0 18 * * 6'

permissions:
  contents: read

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: iNECTA/AL-Go-Actions/WorkflowInitialize@v1.5
        with:
          eventId: "DO0098"

  Update:
    runs-on: [ windows-latest ]
    needs: [ Initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: iNECTA/AL-Go-Actions-INECTA/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl

      - name: Read secrets
        uses: iNECTA/AL-Go-Actions/ReadSecrets@v1.5
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Update AL-Go system files
        uses: iNECTA/AL-Go-Actions-INECTA/CheckForUpdates@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          token: ${{ env.ghTokenWorkflow }}
          Update: Y
          templateUrl: ${{ env.TemplateUrl }}
          directCommit: "Y"

  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, Update ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: iNECTA/AL-Go-Actions/WorkflowPostProcess@v1.5
        with:
          eventId: "DO0098"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
